; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v2 on Tue Aug 06 2019 23:15:45 GMT+0200 (Central European Summer Time)
G1 R1 X0 Y0 Z5 F8000 ; go to 5mm above position of the last print move
G1 R1 X0 Y0          ; go back to the last print move
;G1 E2 F1000 		; Feed 70mm of filament at 800mm/min
M83                  ; relative extruder moves


