; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2 on Tue Aug 06 2019 23:15:45 GMT+0200 (Central European Summer Time)
;M280 P3 S90 I1 ;RepRap2

M280 P0 S90 ;RepRap3

